name: food_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Nới rộng SDK ra một chút để dễ nhận thư viện

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management (STABLE VERSION 2.x)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5 # Bản này ổn định nhất với Generator 2.4.0

  # Navigation
  go_router: ^17.0.1

  # Backend & Storage
  supabase_flutter: ^2.3.0 # Bản ổn định
  flutter_secure_storage: ^9.0.0

  # Data Class Helpers
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generators (Các version này PHẢI khớp nhau)
  build_runner: ^2.4.8
  
  # Riverpod Generator (Ghim bản 2.4.0 để tránh xung đột Analyzer)
  riverpod_generator: ^2.4.0
  
  # Freezed & Json
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  go_router_builder: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/brand/
    - assets/images/social/
    - assets/images/welcome/
  fonts:
    - family: Phosphate
      fonts:
        - asset: assets/fonts/Phosphate/PhosphateSolid.ttf
    - family: PhosphateOutline
      fonts:
        - asset: assets/fonts/Phosphate/PhosphateInline.ttf
    - family: Sofia
      fonts:
        - asset: assets/fonts/SofiaPro/sofiapro-light.otf
    - family: SofiaBold
      fonts:
        - asset: assets/fonts/SofiaPro/sofiapro-light.otf
          weight: 700